### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [rupertoverall/Rtrack#2]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`Rtrack` imports 'rgeos' using `rgeos::gDifference` as found by pkgapi, NAMESPACE also declares `gArea`, `gArea` in R/calculate_metrics.R, `gDifference` in R/plot_density.R. The package also imports `raster`, so `rgeos::gArea` might be replaced by `raster::area` and `rgeos::gDifference` by `sf::st_difference` - there may be an equivalent topological operator in `terra` - used by `raster`, but I have not looked carefully enough. Please fix best by June, latest by October 2023.

**Comment by rupertoverall** [comment]
The update of Rtrack (utilising the `terra` package) is under way and a new version (without `sp`/`rgeos` dependencies) will be released soon.

**Comment by rsbivand** [comment]
@rupertoverall Less than three months remain to retain this package on CRAN. See also https://r-spatial.org/r/2023/05/15/evolution4.html.  Progress on this would be very welcome.

**Comment by rupertoverall** [comment]
The transition to `terra` is complete and working well (actually slightly faster than before). The new release of the Rtrack package is coupled with a major rewrite with additional functionality though, so the final rough edges of that work are being ironed out now. It should be ready for submission to CRAN in the next few weeks.

**Comment by rupertoverall** [comment]
The new version (2.0.2) has just been released to CRAN. This version no longer depends on `sp` or `rgeos`.
