### ISSUE TITLE
support for DeepLabCut files?

### ISSUE THREAD

**Issue by kmh005** [rupertoverall/Rtrack#4]
Hello,
Your software looks really promising!
Do you have plans to add DeepLabCut's hdf5 or csv files as supported file types?
I'd be more than happy to share a few files.
Thanks,
kmh005

**Comment by rupertoverall** [comment]
Ultimately yes, but this will also require support for new experiment types (I don't think anyone uses DLC just for single-point positional tracking) so it is part of a longer-term development plan. Rtrack v3 will look into this.
